import { type Card } from "./CardManager";

// 청크 단위로 카드 로딩하는 함수 추가
export function loadCardChunks(pageSize = 20) {
  const totalCards = cardList.length;
  const cardChunks: Card[][] = [];

  for (let i = 0; i < totalCards; i += pageSize) {
    const chunk = cardList.slice(i, i + pageSize);
    cardChunks.push(chunk);
  }

  return cardChunks;
}

export function getCardsByPage(page = 1, pageSize = 20) {
  const startIndex = (page - 1) * pageSize;
  return cardList.slice(startIndex, startIndex + pageSize);
}

// 기본 카드 상태 (모든 카드에 공통으로 적용될 초기 상태)
const defaultCardState = {
  is_animating: false,
  is_fading_in: false,
  is_fading_out: false,
  is_flipped: false,
  is_selected: false,
  is_tapped: false,
};

// 샘플 카드 데이터
export const cardList: Card[] = [
  {
    serial_number: "IMS002B-115",
    name: "후쿠마루 코이토",
    description: "만물을 위조하는 자",
    image_url:
      "https://s3-ap-northeast-1.amazonaws.com/rebirth-fy.com/wordpress/wp-content/uploads/2025/03/RB_IMS_002B_115RRR.png",
    atk: 3,
    hp: 8,
    type: "character",
    subtype: "member",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "CP-0001_1",
    name: "토오루",
    description: "のびしろ",
    image_url:
      "https://s3-ap-northeast-1.amazonaws.com/rebirth-fy.com/wordpress/wp-content/uploads/2025/03/RB_IMS_002B_095RRR.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "CP-0001_2",
    name: "마도카",
    description: "のびしろ",
    image_url:
      "https://s3-ap-northeast-1.amazonaws.com/rebirth-fy.com/wordpress/wp-content/uploads/2025/03/RB_IMS_002B_105RRR.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  // 여기에 더 많은 카드 추가 (총 카드 수를 적절히 늘려주세요)
  {
    serial_number: "CP-0001_4",
    name: "히나나",
    description: "のびしろ",
    image_url:
      "https://s3-ap-northeast-1.amazonaws.com/rebirth-fy.com/wordpress/wp-content/uploads/2025/03/RB_IMS_002B_125RRR.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P001",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-001sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P002",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-002s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P003",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-003s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P004",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-004s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P005",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-005s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P006",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-006s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P007",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-007s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P008",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-008sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P009",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-009s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },

  {
    serial_number: "P01",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-001sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P02",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-002s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P03",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-003s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P04",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-004s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P05",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-005s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P06",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-006s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P07",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-007s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P08",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-008sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P09",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-009s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P11110",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-010s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0111",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-011s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0112",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-012s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0113",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-013s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0114",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-014s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0115",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-015sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0116",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-016s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0117",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-017s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0118",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-018s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0119",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-019s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P0120",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-020s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P021",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-021s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P022",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-022sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P023",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-023s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P024",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-024s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P025",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-025s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P026",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-026s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P027",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-027s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P028",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-028s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P029",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-029sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P030",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-030s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P031",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-031s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P032",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-032s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P033",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-033s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P034",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-034s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P035",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-035s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P036",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-036sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P037",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-037s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P038",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-038s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P039",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-039s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P040",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-040s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P041",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-041s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P042",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-042s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P043",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-043sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P044",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-044s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P045",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-045s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P046",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-046s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P047",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-047s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P048",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-048s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P049",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-049s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P050",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-050sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P051",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-051s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P052",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-052s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P053",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-053s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P054",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-054s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P055",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-055s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P056",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-056s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P057",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-057sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P058",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-058s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P059",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-059s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P060",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-060s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P061",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-061s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: true,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P062",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-062s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P063",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-063s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P064",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-064sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P065",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-065s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P066",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-066s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P067",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-067s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P068",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-068s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P069",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-069s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P070",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-070s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P071",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-071sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P072",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-072s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P073",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-073s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P074",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-074s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P075",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-075s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P076",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-076s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P077",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-077s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P078",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-078sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P079",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-079s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P080",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-080s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P081",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-081s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P082",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-082s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P083",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-083s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P084",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-084s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P085",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-085sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P086",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-086s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P087",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-087s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P088",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-088s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P089",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-089s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P090",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-090s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P091",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-091s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P092",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-092sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P093",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-093s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P094",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-094s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P095",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-095s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P096",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-096s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P097",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-097s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P098",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-098s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P099",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-099sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P100",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-100s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P101",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-101s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P102",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-102s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P103",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-103s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P104",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-104s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P105",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-105s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P106",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-106sp.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P107",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-107s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P108",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-108s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P110",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-110s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P111",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-111s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P112",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-112s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P113",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-113s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P114",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-114s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P115",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-115s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P116",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-116s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P118",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-118s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P119",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-119s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P120",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-120s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P121",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-121s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P122",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-122s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P123",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-123s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P124",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-124s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },
  {
    serial_number: "P125",
    name: "충성스러운 파트너",
    description: "자신의 턴에 한 번, 데미지를 1 줄일 수 있습니다",
    image_url: "/shiny/ims001b-125s.png",
    atk: 1,
    hp: 3,
    type: "partner",
    subtype: "guard",
    zone: "deck",
    is_first_entry: false,
    state: { ...defaultCardState },
  },

  // 추가 카드들...
];

// 카드 ID로 카드 찾기 함수
export function findCardBySerialNumber(serialNumber: string): Card | undefined {
  return cardList.find((card) => card.serial_number === serialNumber);
}

// 카드 타입별로 필터링하는 함수
export function filterCardsByType(type: Card["type"]): Card[] {
  return cardList.filter((card) => card.type === type);
}
