// Generated from revue.csv on 2025-03-31T06:17:54.049Z
// Do not edit this file manually!

export interface CardDefinition {
  name: string;
  description: string;
  image_url: string;
  atk: number;
  hp: number;
  type: "character" | "re-birth" | "partner";
  subtype: "member" | "spark" | "guard" | "cancel";
  is_first_entry: boolean;
}

export const cardDatabase: Record<string, CardDefinition> = {
  "RS/001B-001": {
    name: "アーサー 華恋",
    description:
      "【永】【エントリー】【Reコンボ】《大道具室のアーサー王！？》【本領発揮Lv４】：あなたのメンバーに《ひかり》がいるなら、このキャラを＋３/±０。【永】【エントリー】【本領発揮Lv４】：あなたのリタイアが相手より少ないなら、あなたのメンバーは相手から選ばれない。",
    image_url: "",
    atk: 4,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-001SP": {
    name: "アーサー 華恋",
    description:
      "【永】【エントリー】【Reコンボ】《大道具室のアーサー王！？》【本領発揮Lv４】：あなたのメンバーに《ひかり》がいるなら、このキャラを＋３/±０。【永】【エントリー】【本領発揮Lv４】：あなたのリタイアが相手より少ないなら、あなたのメンバーは相手から選ばれない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-001sp.png",
    atk: 4,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-002": {
    name: "シャーロック・ホームズ 華恋",
    description:
      "【自】【メンバー】【本領発揮Lv４】〔聖翔音楽学園〕【ターン１】：このキャラがサポートした時、あなたは自分の手札から１枚控え室に置くことで、相手のメンバーから１枚選び、エネルギーに置き、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-002.png",
    atk: 4,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-002S": {
    name: "シャーロック・ホームズ 華恋",
    description:
      "【自】【メンバー】【本領発揮Lv４】〔聖翔音楽学園〕【ターン１】：このキャラがサポートした時、あなたは自分の手札から１枚控え室に置くことで、相手のメンバーから１枚選び、エネルギーに置き、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-002s.png",
    atk: 4,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-003": {
    name: "銃士ダルタニャン 華恋",
    description:
      "【キャンセル】：Reバース以外の【スパーク】（手札から控え室に置くと、Reバース以外の【スパーク】を１つ止める）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-003.png",
    atk: 4,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-003S": {
    name: "銃士ダルタニャン 華恋",
    description:
      "【キャンセル】：Reバース以外の【スパーク】（手札から控え室に置くと、Reバース以外の【スパーク】を１つ止める）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-003s.png",
    atk: 4,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-004": {
    name: "愛城 華恋",
    description:
      "【スパーク】【本領発揮Lv５】：あなたは自分の控え室から《ひかり》を１枚選び、メンバーに置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-004.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-004S": {
    name: "愛城 華恋",
    description:
      "【スパーク】【本領発揮Lv５】：あなたは自分の控え室から《ひかり》を１枚選び、メンバーに置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-004s.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-005": {
    name: "銃士アトス ひかり",
    description:
      "【自】【エントリー】【Reコンボ】《一人は皆のために》【本領発揮Lv５】【ターン１】：このキャラがアタックした時、あなたのメンバーに《華恋》がいるなら、あなたは２枚引き、このアタック中、相手は【ブロッカー】を使えない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-005.png",
    atk: 5,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-005SP": {
    name: "銃士アトス ひかり",
    description:
      "【自】【エントリー】【Reコンボ】《一人は皆のために》【本領発揮Lv５】【ターン１】：このキャラがアタックした時、あなたのメンバーに《華恋》がいるなら、あなたは２枚引き、このアタック中、相手は【ブロッカー】を使えない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-005sp.png",
    atk: 5,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-006": {
    name: "ガウェイン ひかり",
    description:
      "【永】【メンバー】【本領発揮Lv４】：あなたのエントリーの、《華恋》か《ひかり》を＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-006.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-006S": {
    name: "ガウェイン ひかり",
    description:
      "【永】【メンバー】【本領発揮Lv４】：あなたのエントリーの、《華恋》か《ひかり》を＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-006s.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-007": {
    name: "神楽 ひかり",
    description:
      "【自】【本領発揮Lv４】：このキャラがメンバーに置かれた時、あなたは１枚引き、自分の手札から１枚控え室に置く。（エントリーインより優先）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-007.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-007S": {
    name: "神楽 ひかり",
    description:
      "【自】【本領発揮Lv４】：このキャラがメンバーに置かれた時、あなたは１枚引き、自分の手札から１枚控え室に置く。（エントリーインより優先）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-007s.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-008": {
    name: "太陽の国の軍団長 真矢",
    description:
      "【起】【メンバー】【Reコンボ】《友情と悲しみの騎士二人》【本領発揮Lv４】【ターン１】：［エネ①］ あなたは相手のメンバーからすべて選び、控え室に置く。【永】【エントリー】【本領発揮Lv４】：あなたのメンバーが相手より多いなら、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-008.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-008SP": {
    name: "太陽の国の軍団長 真矢",
    description:
      "【起】【メンバー】【Reコンボ】《友情と悲しみの騎士二人》【本領発揮Lv４】【ターン１】：［エネ①］ あなたは相手のメンバーからすべて選び、控え室に置く。【永】【エントリー】【本領発揮Lv４】：あなたのメンバーが相手より多いなら、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-008sp.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-009": {
    name: "メイド メリッサ 真矢",
    description:
      "【自】【エントリー】【ターン１】：このキャラがアタックされた時、あなたは味方のデッキの上から１枚控え室に置く。それがコスト４以上のキャラなら、このアタックのダメージを０にする。（パートナーアタックは防げない）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-009.png",
    atk: 5,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-009S": {
    name: "メイド メリッサ 真矢",
    description:
      "【自】【エントリー】【ターン１】：このキャラがアタックされた時、あなたは味方のデッキの上から１枚控え室に置く。それがコスト４以上のキャラなら、このアタックのダメージを０にする。（パートナーアタックは防げない）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-009s.png",
    atk: 5,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-010": {
    name: "天堂 真矢",
    description:
      "【自】【メンバー】：このキャラがサポートした時、あなたはエネ①することで、相手のエントリーからDEF２以上のキャラを１枚選び、このアタック中、そのキャラを±０/－１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-010.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-010S": {
    name: "天堂 真矢",
    description:
      "【自】【メンバー】：このキャラがサポートした時、あなたはエネ①することで、相手のエントリーからDEF２以上のキャラを１枚選び、このアタック中、そのキャラを±０/－１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-010s.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-011": {
    name: "ロビンフッド 純那",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは自分のメンバーから１枚選び、エネルギーに【レスト】で置いてよい。【永】【エントリー】【本領発揮Lv４】：このキャラを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-011.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-011SP": {
    name: "ロビンフッド 純那",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは自分のメンバーから１枚選び、エネルギーに【レスト】で置いてよい。【永】【エントリー】【本領発揮Lv４】：このキャラを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-011sp.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-012": {
    name: "銃士アラミス 純那",
    description:
      "【自】【エントリー】【本領発揮Lv４】：あなたのターン終了時、このターンこのキャラが相手のキャラを３枚リタイアさせたなら、あなたは相手のメンバーからすべて選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-012.png",
    atk: 3,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-012S": {
    name: "銃士アラミス 純那",
    description:
      "【自】【エントリー】【本領発揮Lv４】：あなたのターン終了時、このターンこのキャラが相手のキャラを３枚リタイアさせたなら、あなたは相手のメンバーからすべて選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-012s.png",
    atk: 3,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-013": {
    name: "星見 純那",
    description:
      "【スパーク】【本領発揮Lv３】：あなたは相手のエントリーから１枚選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-013.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-013S": {
    name: "星見 純那",
    description:
      "【スパーク】【本領発揮Lv３】：あなたは相手のエントリーから１枚選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-013s.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-014": {
    name: "銃士ポルトス まひる",
    description:
      "【自】【エントリー】【本領発揮Lv４】：このキャラのアタック終了時、あなたは自分の控え室から、《華恋》か《ひかり》か《純那》を１枚選び、エントリーに置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-014.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-014SP": {
    name: "銃士ポルトス まひる",
    description:
      "【自】【エントリー】【本領発揮Lv４】：このキャラのアタック終了時、あなたは自分の控え室から、《華恋》か《ひかり》か《純那》を１枚選び、エントリーに置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-014sp.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-015": {
    name: "人魚姫 まひる",
    description:
      "【スパーク】：あなたは味方のメンバーから２枚選び、控え室に置くことで、手札から２枚エネルギーに【レスト】で置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-015.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-015S": {
    name: "人魚姫 まひる",
    description:
      "【スパーク】：あなたは味方のメンバーから２枚選び、控え室に置くことで、手札から２枚エネルギーに【レスト】で置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-015s.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-016": {
    name: "露崎 まひる",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-016.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-016S": {
    name: "露崎 まひる",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-016s.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-017": {
    name: "ファントム なな",
    description:
      "【スパーク】【本領発揮Lv５】：あなたは２枚引き、自分の手札から１枚デッキの下に置く。【永】【エントリー】【Reコンボ】《ファントムとクリスティーヌ》【本領発揮Lv５】：このキャラを＋４/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-017.png",
    atk: 4,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-017SP": {
    name: "ファントム なな",
    description:
      "【スパーク】【本領発揮Lv５】：あなたは２枚引き、自分の手札から１枚デッキの下に置く。【永】【エントリー】【Reコンボ】《ファントムとクリスティーヌ》【本領発揮Lv５】：このキャラを＋４/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-017sp.png",
    atk: 4,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-018": {
    name: "マーリン なな",
    description:
      "【スパーク】【本領発揮Lv３】〔聖翔音楽学園〕：あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-018.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-018S": {
    name: "マーリン なな",
    description:
      "【スパーク】【本領発揮Lv３】〔聖翔音楽学園〕：あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-018s.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-019": {
    name: "大場 なな",
    description:
      "【スパーク】：相手のターンの終わりまで、このキャラを－６/－６。【自】：このキャラがあなたのターン中に手札からエントリーに置かれた時、あなたのメンバーに《ひかり》がいないなら、あなたは自分の、メンバーと控え室からキャラを望む枚数選び、それらを入れ替える。このフェイズを終了する。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-019.png",
    atk: 7,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-019S": {
    name: "大場 なな",
    description:
      "【スパーク】：相手のターンの終わりまで、このキャラを－６/－６。【自】：このキャラがあなたのターン中に手札からエントリーに置かれた時、あなたのメンバーに《ひかり》がいないなら、あなたは自分の、メンバーと控え室からキャラを望む枚数選び、それらを入れ替える。このフェイズを終了する。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-019s.png",
    atk: 7,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-020": {
    name: "アラジン クロディーヌ",
    description:
      "【自】【エントリー】【Reコンボ】《月夜のデュエット》【本領発揮Lv４】【ターン１】：このキャラがアタックした時、あなたは自分のメンバーから１枚選び、エネルギーに置き、味方のパートナーをすべて【スタンド】する。【永】【エントリー】：各ターンこのキャラの１回目のアタック中、このキャラを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-020.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-020SP": {
    name: "アラジン クロディーヌ",
    description:
      "【自】【エントリー】【Reコンボ】《月夜のデュエット》【本領発揮Lv４】【ターン１】：このキャラがアタックした時、あなたは自分のメンバーから１枚選び、エネルギーに置き、味方のパートナーをすべて【スタンド】する。【永】【エントリー】：各ターンこのキャラの１回目のアタック中、このキャラを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-020sp.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-021": {
    name: "くるみ割り人形 クロディーヌ",
    description:
      "【自】【メンバー】【本領発揮Lv５】〔聖翔音楽学園〕：このキャラがサポートした時、相手のメンバーに空席があるなら、あなたはこのキャラをデッキの下に置くことで、このアタック中、サポートされたキャラを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-021.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-021S": {
    name: "くるみ割り人形 クロディーヌ",
    description:
      "【自】【メンバー】【本領発揮Lv５】〔聖翔音楽学園〕：このキャラがサポートした時、相手のメンバーに空席があるなら、あなたはこのキャラをデッキの下に置くことで、このアタック中、サポートされたキャラを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-021s.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-022": {
    name: "西條 クロディーヌ",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-022.png",
    atk: 5,
    hp: 9,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-022S": {
    name: "西條 クロディーヌ",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-022s.png",
    atk: 5,
    hp: 9,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-023": {
    name: "清水次郎長 双葉",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは自分の手札から１枚控え室に置くことで、控え室からReバースを１枚セットする。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-023.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-023SP": {
    name: "清水次郎長 双葉",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは自分の手札から１枚控え室に置くことで、控え室からReバースを１枚セットする。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-023sp.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-024": {
    name: "長靴をはいた猫 双葉",
    description:
      "【スパーク】：このターンこのキャラの次のアタック中、相手は【ブロッカー】を使えない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-024.png",
    atk: 4,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-024S": {
    name: "長靴をはいた猫 双葉",
    description:
      "【スパーク】：このターンこのキャラの次のアタック中、相手は【ブロッカー】を使えない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-024s.png",
    atk: 4,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-025": {
    name: "石動 双葉",
    description: "【スパーク】：このターン中、このキャラを＋２/＋２。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-025.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-025S": {
    name: "石動 双葉",
    description: "【スパーク】：このターン中、このキャラを＋２/＋２。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-025s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-026": {
    name: "悪戯なコウモリの魔女 香子",
    description:
      "【起】【エントリー】【Reコンボ】《トリック・オア・トリート》【本領発揮Lv７】【ターン１】：［エネ①］ あなたは相手のメンバーから２枚選び、次の相手のターン中、それらは【スタンド】しない。【起】【エントリー】：［エネ②］ このターン中、このキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-026.png",
    atk: 5,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-026SP": {
    name: "悪戯なコウモリの魔女 香子",
    description:
      "【起】【エントリー】【Reコンボ】《トリック・オア・トリート》【本領発揮Lv７】【ターン１】：［エネ①］ あなたは相手のメンバーから２枚選び、次の相手のターン中、それらは【スタンド】しない。【起】【エントリー】：［エネ②］ このターン中、このキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-026sp.png",
    atk: 5,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-027": {
    name: "黒獅子の国の軍団長 香子",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは相手のメンバーから１枚選び、次の相手のターン中、そのキャラは【スタンド】しない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-027.png",
    atk: 3,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-027S": {
    name: "黒獅子の国の軍団長 香子",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは相手のメンバーから１枚選び、次の相手のターン中、そのキャラは【スタンド】しない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-027s.png",
    atk: 3,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-028": {
    name: "花柳 香子",
    description:
      "【スパーク】【本領発揮Lv３】：あなたは自分のメンバーから《珠緒》を１枚選び、エネルギーに【レスト】で置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-028.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-028S": {
    name: "花柳 香子",
    description:
      "【スパーク】【本領発揮Lv３】：あなたは自分のメンバーから《珠緒》を１枚選び、エネルギーに【レスト】で置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-028s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-029": {
    name: "乙姫 珠緒",
    description:
      "【永】【エントリー】【Reコンボ】《「浦島太郎」公演のお知らせ》【本領発揮Lv４】：あなたのメンバーは相手から選ばれず、このキャラを＋３/±０。【永】【エントリー】：各ターン相手の１回目のアタックはパートナーアタックにならない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-029.png",
    atk: 3,
    hp: 9,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-029SP": {
    name: "乙姫 珠緒",
    description:
      "【永】【エントリー】【Reコンボ】《「浦島太郎」公演のお知らせ》【本領発揮Lv４】：あなたのメンバーは相手から選ばれず、このキャラを＋３/±０。【永】【エントリー】：各ターン相手の１回目のアタックはパートナーアタックにならない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-029sp.png",
    atk: 3,
    hp: 9,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-030": {
    name: "あやかし見廻り隊 副長 珠緒",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは自分のデッキの上から１枚エネルギーに【レスト】で置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-030.png",
    atk: 3,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-030S": {
    name: "あやかし見廻り隊 副長 珠緒",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは自分のデッキの上から１枚エネルギーに【レスト】で置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-030s.png",
    atk: 3,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-031": {
    name: "巴 珠緒",
    description:
      "【自】【メンバー】：このキャラが〔凛明館女学校〕をサポートした時、あなたはこのキャラをデッキの下に置くことで、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-031.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-031S": {
    name: "巴 珠緒",
    description:
      "【自】【メンバー】：このキャラが〔凛明館女学校〕をサポートした時、あなたはこのキャラをデッキの下に置くことで、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-031s.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-032": {
    name: "武蔵坊弁慶 珠緒",
    description:
      "【自】：このキャラが手札からエントリーに置かれた時、このターン中、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-032.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-032S": {
    name: "武蔵坊弁慶 珠緒",
    description:
      "【自】：このキャラが手札からエントリーに置かれた時、このターン中、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-032s.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-033": {
    name: "あやかし見廻り隊 隊長 いちえ",
    description:
      "【起】【メンバー】【Reコンボ】《帝都の平和を守るもの達》【ターン１】：［エネルギーから１枚控え室に置く］ あなたは自分の手札から〔凛明館女学校〕を１枚選び、エントリーに置き、１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-033.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-033SP": {
    name: "あやかし見廻り隊 隊長 いちえ",
    description:
      "【起】【メンバー】【Reコンボ】《帝都の平和を守るもの達》【ターン１】：［エネルギーから１枚控え室に置く］ あなたは自分の手札から〔凛明館女学校〕を１枚選び、エントリーに置き、１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-033sp.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-034": {
    name: "烏天狗 いちえ",
    description:
      "【自】【メンバー】【本領発揮Lv５】〔凛明館女学校〕：あなたのメインフェイズ開始時、あなたはこのキャラをデッキの下に置くことで、１枚引き、相手のメンバーからすべて選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-034.png",
    atk: 3,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-034S": {
    name: "烏天狗 いちえ",
    description:
      "【自】【メンバー】【本領発揮Lv５】〔凛明館女学校〕：あなたのメインフェイズ開始時、あなたはこのキャラをデッキの下に置くことで、１枚引き、相手のメンバーからすべて選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-034s.png",
    atk: 3,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-035": {
    name: "音無 いちえ",
    description:
      "【自】【本領発揮Lv５】【ターン１】：このキャラが相手のキャラをリタイアさせた時、あなたは自分の手札から１枚控え室に置くことで、デッキの上から２枚エネルギーに置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-035.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-035S": {
    name: "音無 いちえ",
    description:
      "【自】【本領発揮Lv５】【ターン１】：このキャラが相手のキャラをリタイアさせた時、あなたは自分の手札から１枚控え室に置くことで、デッキの上から２枚エネルギーに置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-035s.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-036": {
    name: "天使の歌声 いちえ",
    description:
      "【自】【メンバー】【本領発揮Lv４】：このキャラがサポートした時、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-036.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-036S": {
    name: "天使の歌声 いちえ",
    description:
      "【自】【メンバー】【本領発揮Lv４】：このキャラがサポートした時、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-036s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-037": {
    name: "酒吞童子 文",
    description:
      "【自】：このキャラが手札からエントリーに置かれた時、あなたのメンバーに〔凛明館女学校〕がいるなら、あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-037.png",
    atk: 5,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-037SP": {
    name: "酒吞童子 文",
    description:
      "【自】：このキャラが手札からエントリーに置かれた時、あなたのメンバーに〔凛明館女学校〕がいるなら、あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-037sp.png",
    atk: 5,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-038": {
    name: "弁財天 文",
    description:
      "【自】【メンバー】【本領発揮Lv４】：あなたのメインフェイズ開始時、あなたはこのキャラをデッキの下に置くことで、自分のデッキの上から２枚エネルギーに置き、エネルギーから１枚選び、手札に戻す。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-038.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-038S": {
    name: "弁財天 文",
    description:
      "【自】【メンバー】【本領発揮Lv４】：あなたのメインフェイズ開始時、あなたはこのキャラをデッキの下に置くことで、自分のデッキの上から２枚エネルギーに置き、エネルギーから１枚選び、手札に戻す。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-038s.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-039": {
    name: "夢大路 文",
    description:
      "【自】【メンバー】：あなたの《栞》がエントリーに置かれた時、あなたはこのキャラを控え室に置く。（この効果は強制）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-039.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-039S": {
    name: "夢大路 文",
    description:
      "【自】【メンバー】：あなたの《栞》がエントリーに置かれた時、あなたはこのキャラを控え室に置く。（この効果は強制）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-039s.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-040": {
    name: "あやかし見廻り隊 隊士 文",
    description:
      "【スパーク】：あなたは相手の、エントリーかメンバーから１枚選び、このターン中、そのキャラは【永】をすべて失う。(【キャンセル】と【ブロッカー】とのびしろも失われる)",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-040.png",
    atk: 5,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-040S": {
    name: "あやかし見廻り隊 隊士 文",
    description:
      "【スパーク】：あなたは相手の、エントリーかメンバーから１枚選び、このターン中、そのキャラは【永】をすべて失う。(【キャンセル】と【ブロッカー】とのびしろも失われる)",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-040s.png",
    atk: 5,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-041": {
    name: "鬼影 塁",
    description:
      "【ブロッカー】（手札から控え室に置くと、味方へのアタック１回のダメージを０にする）【起】【控え室】【本領発揮Lv８】〔凛明館女学校〕：［エネ④］ あなたはこのキャラを手札に戻す。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-041.png",
    atk: 3,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-041SP": {
    name: "鬼影 塁",
    description:
      "【ブロッカー】（手札から控え室に置くと、味方へのアタック１回のダメージを０にする）【起】【控え室】【本領発揮Lv８】〔凛明館女学校〕：［エネ④］ あなたはこのキャラを手札に戻す。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-041sp.png",
    atk: 3,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-042": {
    name: "柳生十兵衛 塁",
    description:
      "【自】【エントリー】：このキャラがアタックした時、あなたは味方の【スタンド】しているメンバーから１枚選び、【レスト】することで、このアタック中、相手は【ブロッカー】を使えない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-042.png",
    atk: 5,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-042S": {
    name: "柳生十兵衛 塁",
    description:
      "【自】【エントリー】：このキャラがアタックした時、あなたは味方の【スタンド】しているメンバーから１枚選び、【レスト】することで、このアタック中、相手は【ブロッカー】を使えない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-042s.png",
    atk: 5,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-043": {
    name: "秋風 塁",
    description:
      "【永】【エントリー】：各ターンこのキャラの１回目のアタック中、あなたのメンバーに《珠緒》がいるなら、このキャラを＋５/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-043.png",
    atk: 4,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-043S": {
    name: "秋風 塁",
    description:
      "【永】【エントリー】：各ターンこのキャラの１回目のアタック中、あなたのメンバーに《珠緒》がいるなら、このキャラを＋５/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-043s.png",
    atk: 4,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-044": {
    name: "あやかし見廻り隊 隊士 塁",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-044.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-044S": {
    name: "あやかし見廻り隊 隊士 塁",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-044s.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-045": {
    name: "風魔小太郎 ゆゆ子",
    description:
      "【永】【エントリー】【本領発揮Lv６】：あなたのエネルギーが５枚以上なら、あなたのメンバーは相手から選ばれない。【自】【本領発揮Lv６】：このキャラが手札からエントリーに置かれた時、あなたは自分の控え室から〔凛明館女学校〕を１枚選び、エネルギーに【レスト】で置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-045.png",
    atk: 4,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-045SP": {
    name: "風魔小太郎 ゆゆ子",
    description:
      "【永】【エントリー】【本領発揮Lv６】：あなたのエネルギーが５枚以上なら、あなたのメンバーは相手から選ばれない。【自】【本領発揮Lv６】：このキャラが手札からエントリーに置かれた時、あなたは自分の控え室から〔凛明館女学校〕を１枚選び、エネルギーに【レスト】で置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-045sp.png",
    atk: 4,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-046": {
    name: "源義経 ゆゆ子",
    description:
      "【スパーク】【本領発揮Lv３】：このターン中、このキャラを＋３/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-046.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-046S": {
    name: "源義経 ゆゆ子",
    description:
      "【スパーク】【本領発揮Lv３】：このターン中、このキャラを＋３/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-046s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-047": {
    name: "田中 ゆゆ子",
    description:
      "【永】【エントリー】：あなたのメンバーに《純那》がいるなら、このキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-047.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-047S": {
    name: "田中 ゆゆ子",
    description:
      "【永】【エントリー】：あなたのメンバーに《純那》がいるなら、このキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-047s.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-048": {
    name: "あやかし見廻り隊 隊士 ゆゆ子",
    description:
      "【起】【メンバー】【ターン１】：［このキャラを【レスト】する］ あなたのエネルギーが５枚以上なら、あなたは１枚引く。【起】【メンバー】：［エネ③］ このキャラを【スタンド】する。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-048.png",
    atk: 4,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-048S": {
    name: "あやかし見廻り隊 隊士 ゆゆ子",
    description:
      "【起】【メンバー】【ターン１】：［このキャラを【レスト】する］ あなたのエネルギーが５枚以上なら、あなたは１枚引く。【起】【メンバー】：［エネ③］ このキャラを【スタンド】する。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-048s.png",
    atk: 4,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-049": {
    name: "イースターバニー あるる",
    description:
      "【スパーク】【本領発揮Lv５】〔フロンティア芸術学校〕：あなたは自分のメンバーから１枚選び、控え室に置くことで、相手のメンバーから１枚選び、控え室に置く。【起】【エントリー】【Reコンボ】《私色に染まった卵》【本領発揮Lv５】【ターン１】： あなたは１枚引き、自分の手札からキャラを１枚まで選び、メンバーに置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-049.png",
    atk: 6,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-049SP": {
    name: "イースターバニー あるる",
    description:
      "【スパーク】【本領発揮Lv５】〔フロンティア芸術学校〕：あなたは自分のメンバーから１枚選び、控え室に置くことで、相手のメンバーから１枚選び、控え室に置く。【起】【エントリー】【Reコンボ】《私色に染まった卵》【本領発揮Lv５】【ターン１】： あなたは１枚引き、自分の手札からキャラを１枚まで選び、メンバーに置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-049sp.png",
    atk: 6,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-050": {
    name: "駆け出し船長 あるる",
    description:
      "【自】【メンバー】：このキャラがサポートした時、あなたはこのキャラをデッキの下に置くことで、このアタック中、サポートされたキャラを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-050.png",
    atk: 3,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-050S": {
    name: "駆け出し船長 あるる",
    description:
      "【自】【メンバー】：このキャラがサポートした時、あなたはこのキャラをデッキの下に置くことで、このアタック中、サポートされたキャラを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-050s.png",
    atk: 3,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-051": {
    name: "大月 あるる",
    description:
      "【スパーク】【本領発揮Lv４】〔フロンティア芸術学校〕：あなたは相手のメンバーから１枚選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-051.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-051S": {
    name: "大月 あるる",
    description:
      "【スパーク】【本領発揮Lv４】〔フロンティア芸術学校〕：あなたは相手のメンバーから１枚選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-051s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-052": {
    name: "妖精の魔法使い あるる",
    description:
      "【起】【エントリー】：［エネ③］ このターン中、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-052.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-052S": {
    name: "妖精の魔法使い あるる",
    description:
      "【起】【エントリー】：［エネ③］ このターン中、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-052s.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-053": {
    name: "ドン・キホーテ 美空",
    description:
      "【自】【本領発揮Lv４】：このキャラが手札からメンバーに置かれた時、あなたは自分のエントリーから〔フロンティア芸術学校〕を１枚選び、このターンそのキャラの次のアタック中、相手は【ブロッカー】を使えない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-053.png",
    atk: 4,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-053SP": {
    name: "ドン・キホーテ 美空",
    description:
      "【自】【本領発揮Lv４】：このキャラが手札からメンバーに置かれた時、あなたは自分のエントリーから〔フロンティア芸術学校〕を１枚選び、このターンそのキャラの次のアタック中、相手は【ブロッカー】を使えない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-053sp.png",
    atk: 4,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-054": {
    name: "駆け出し操舵士 美空",
    description:
      "【ブロッカー】（手札から控え室に置くと、味方へのアタック１回のダメージを０にする）【起】【メンバー】【本領発揮Lv７】：［エネ①］ あなたのエントリーに《あるる》がいるなら、あなたはこのキャラをデッキの下に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-054.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-054S": {
    name: "駆け出し操舵士 美空",
    description:
      "【ブロッカー】（手札から控え室に置くと、味方へのアタック１回のダメージを０にする）【起】【メンバー】【本領発揮Lv７】：［エネ①］ あなたのエントリーに《あるる》がいるなら、あなたはこのキャラをデッキの下に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-054s.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-055": {
    name: "叶 美空",
    description: "【スパーク】：このターン中、このキャラを＋２/＋２。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-055.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-055S": {
    name: "叶 美空",
    description: "【スパーク】：このターン中、このキャラを＋２/＋２。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-055s.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-056": {
    name: "パンドラ 美空",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-056.png",
    atk: 2,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-056S": {
    name: "パンドラ 美空",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-056s.png",
    atk: 2,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-057": {
    name: "シンデレラ ララフィン",
    description:
      "【起】【メンバー】【Reコンボ】《新シンデレラは正義の味方！》【本領発揮Lv４】【ターン１】：［エネ①］ あなたは１枚引き、自分のエントリーから〔フロンティア芸術学校〕を１枚選び、デッキの下に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-057.png",
    atk: 4,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-057SP": {
    name: "シンデレラ ララフィン",
    description:
      "【起】【メンバー】【Reコンボ】《新シンデレラは正義の味方！》【本領発揮Lv４】【ターン１】：［エネ①］ あなたは１枚引き、自分のエントリーから〔フロンティア芸術学校〕を１枚選び、デッキの下に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-057sp.png",
    atk: 4,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-058": {
    name: "水兵 ノア ララフィン",
    description:
      "【スパーク】【本領発揮Lv３】〔フロンティア芸術学校〕：あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-058.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-058S": {
    name: "水兵 ノア ララフィン",
    description:
      "【スパーク】【本領発揮Lv３】〔フロンティア芸術学校〕：あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-058s.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-059": {
    name: "野々宮 ララフィン",
    description:
      "【自】：このキャラが相手の効果でメンバーから控え室に置かれた時、あなたはこのキャラを控え室から手札に戻してよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-059.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-059S": {
    name: "野々宮 ララフィン",
    description:
      "【自】：このキャラが相手の効果でメンバーから控え室に置かれた時、あなたはこのキャラを控え室から手札に戻してよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-059s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-060": {
    name: "海賊女王の用心棒 ララフィン",
    description: "【スパーク】：このターン中、このキャラを＋２/＋２。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-060.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-060S": {
    name: "海賊女王の用心棒 ララフィン",
    description: "【スパーク】：このターン中、このキャラを＋２/＋２。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-060s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-061": {
    name: "チェシャ猫 つかさ",
    description:
      "【自】【メンバー】：このキャラが〔フロンティア芸術学校〕をサポートした時、あなたはこのキャラをデッキの下に置くことで、１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-061.png",
    atk: 3,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-061SP": {
    name: "チェシャ猫 つかさ",
    description:
      "【自】【メンバー】：このキャラが〔フロンティア芸術学校〕をサポートした時、あなたはこのキャラをデッキの下に置くことで、１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-061sp.png",
    atk: 3,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-062": {
    name: "謹賀新年！ つかさ",
    description:
      "【自】【メンバー】：このキャラが〔フロンティア芸術学校〕をサポートした時、あなたはこのキャラをデッキの下に置くことで、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-062.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-062S": {
    name: "謹賀新年！ つかさ",
    description:
      "【自】【メンバー】：このキャラが〔フロンティア芸術学校〕をサポートした時、あなたはこのキャラをデッキの下に置くことで、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-062s.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-063": {
    name: "恵比寿 つかさ",
    description:
      "【自】【エントリー】【本領発揮Lv４】【ターン１】：このキャラが相手のキャラをリタイアさせた時、あなたのメンバーに《あるる》がいるなら、あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-063.png",
    atk: 6,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-063S": {
    name: "恵比寿 つかさ",
    description:
      "【自】【エントリー】【本領発揮Lv４】【ターン１】：このキャラが相手のキャラをリタイアさせた時、あなたのメンバーに《あるる》がいるなら、あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-063s.png",
    atk: 6,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-064": {
    name: "ベテラン海賊 つかさ",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは相手のエネルギーから１枚選び、次の相手のターン中、そのエネルギーは【スタンド】しない。このターン中、このキャラを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-064.png",
    atk: 4,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-064S": {
    name: "ベテラン海賊 つかさ",
    description:
      "【スパーク】【本領発揮Lv４】：あなたは相手のエネルギーから１枚選び、次の相手のターン中、そのエネルギーは【スタンド】しない。このターン中、このキャラを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-064s.png",
    atk: 4,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-065": {
    name: "モンテ・クリスト伯 静羽",
    description:
      "【永】【エントリー】【本領発揮Lv４】：このキャラを＋１/±０。【永】【エントリー】【本領発揮Lv６】：このキャラを±０/＋１。【永】【エントリー】【本領発揮Lv８】〔フロンティア芸術学校〕：このキャラを＋２/＋２。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-065.png",
    atk: 5,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-065SP": {
    name: "モンテ・クリスト伯 静羽",
    description:
      "【永】【エントリー】【本領発揮Lv４】：このキャラを＋１/±０。【永】【エントリー】【本領発揮Lv６】：このキャラを±０/＋１。【永】【エントリー】【本領発揮Lv８】〔フロンティア芸術学校〕：このキャラを＋２/＋２。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-065sp.png",
    atk: 5,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-066": {
    name: "水兵長 マリオン 静羽",
    description:
      "【スパーク】【本領発揮Lv５】：あなたは自分のメンバーから１枚選び、エネルギーに【レスト】で置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-066.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-066S": {
    name: "水兵長 マリオン 静羽",
    description:
      "【スパーク】【本領発揮Lv５】：あなたは自分のメンバーから１枚選び、エネルギーに【レスト】で置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-066s.png",
    atk: 4,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-067": {
    name: "胡蝶 静羽",
    description:
      "【スパーク】：あなたは自分の控え室からキャラを１枚選び、メンバーに置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-067.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-067S": {
    name: "胡蝶 静羽",
    description:
      "【スパーク】：あなたは自分の控え室からキャラを１枚選び、メンバーに置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-067s.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-068": {
    name: "海賊女王 静羽",
    description:
      "【スパーク】：あなたは相手のエントリーからDEF４以上のキャラを１枚選び、このターン中、そのキャラを±０/－１し、このキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-068.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-068S": {
    name: "海賊女王 静羽",
    description:
      "【スパーク】：あなたは相手のエントリーからDEF４以上のキャラを１枚選び、このターン中、そのキャラを±０/－１し、このキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-068s.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-069": {
    name: "セイレーン 晶",
    description:
      "【自】【エントリー】【Reコンボ】《乙女の髪結い》【本領発揮Lv５】【ターン１】：このキャラがアタックした時、あなたは自分の控え室から、《ミチル》か【キャンセル】を持つキャラを１枚選び、メンバーに置く。【起】【エントリー】：［エネ③］ あなたは自分の控え室から《乙女の髪結い》を１枚セットする。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-069.png",
    atk: 4,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-069SP": {
    name: "セイレーン 晶",
    description:
      "【自】【エントリー】【Reコンボ】《乙女の髪結い》【本領発揮Lv５】【ターン１】：このキャラがアタックした時、あなたは自分の控え室から、《ミチル》か【キャンセル】を持つキャラを１枚選び、メンバーに置く。【起】【エントリー】：［エネ③］ あなたは自分の控え室から《乙女の髪結い》を１枚セットする。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-069sp.png",
    atk: 4,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-070": {
    name: "天の神 晶",
    description:
      "【スパーク】【本領発揮Lv３】〔シークフェルト音楽学院〕：あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-070.png",
    atk: 3,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-070S": {
    name: "天の神 晶",
    description:
      "【スパーク】【本領発揮Lv３】〔シークフェルト音楽学院〕：あなたは１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-070s.png",
    atk: 3,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-071": {
    name: "雪代 晶",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-071.png",
    atk: 6,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-071S": {
    name: "雪代 晶",
    description: "【のびしろ】（今後の成長に期待！）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-071s.png",
    atk: 6,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-072": {
    name: "野獣 晶",
    description:
      "【キャンセル】：Reバース以外の【スパーク】（手札から控え室に置くと、Reバース以外の【スパーク】を１つ止める）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-072.png",
    atk: 5,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-072S": {
    name: "野獣 晶",
    description:
      "【キャンセル】：Reバース以外の【スパーク】（手札から控え室に置くと、Reバース以外の【スパーク】を１つ止める）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-072s.png",
    atk: 5,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-073": {
    name: "織姫 ミチル",
    description:
      "【永】【メンバー】【本領発揮Lv７】：あなたのエントリーの〔シークフェルト音楽学院〕を＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-073.png",
    atk: 4,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-073SP": {
    name: "織姫 ミチル",
    description:
      "【永】【メンバー】【本領発揮Lv７】：あなたのエントリーの〔シークフェルト音楽学院〕を＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-073sp.png",
    atk: 4,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-074": {
    name: "ハーメルンの笛吹き ミチル",
    description:
      "【自】【メンバー】【本領発揮Lv５】〔シークフェルト音楽学院〕：このキャラがサポートした時、あなたはこのキャラをエネルギーに置くことで、１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-074.png",
    atk: 3,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-074S": {
    name: "ハーメルンの笛吹き ミチル",
    description:
      "【自】【メンバー】【本領発揮Lv５】〔シークフェルト音楽学院〕：このキャラがサポートした時、あなたはこのキャラをエネルギーに置くことで、１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-074s.png",
    atk: 3,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-075": {
    name: "鳳 ミチル",
    description:
      "【ブロッカー】（手札から控え室に置くと、味方へのアタック１回のダメージを０にする）【自】【本領発揮Lv５】：このキャラが《晶》をブロックした時、あなたはこのキャラをエネルギーに置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-075.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-075S": {
    name: "鳳 ミチル",
    description:
      "【ブロッカー】（手札から控え室に置くと、味方へのアタック１回のダメージを０にする）【自】【本領発揮Lv５】：このキャラが《晶》をブロックした時、あなたはこのキャラをエネルギーに置いてよい。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-075s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-076": {
    name: "水の神 ミチル",
    description:
      "【永】【エントリー】【Reコンボ】：あなたのメンバーが３枚以上いるなら、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-076.png",
    atk: 4,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-076S": {
    name: "水の神 ミチル",
    description:
      "【永】【エントリー】【Reコンボ】：あなたのメンバーが３枚以上いるなら、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-076s.png",
    atk: 4,
    hp: 8,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-077": {
    name: "呂布 メイファン",
    description:
      "【永】【エントリー】【本領発揮Lv４】：あなたの、メンバーかリタイアに《晶》がいるなら、このキャラを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-077.png",
    atk: 5,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-077SP": {
    name: "呂布 メイファン",
    description:
      "【永】【エントリー】【本領発揮Lv４】：あなたの、メンバーかリタイアに《晶》がいるなら、このキャラを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-077sp.png",
    atk: 5,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-078": {
    name: "カンフースター メイファン",
    description:
      "【スパーク】：あなたのリタイア２枚につき、このターン中、このキャラを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-078.png",
    atk: 3,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-078S": {
    name: "カンフースター メイファン",
    description:
      "【スパーク】：あなたのリタイア２枚につき、このターン中、このキャラを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-078s.png",
    atk: 3,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-079": {
    name: "リュウ・メイファン",
    description:
      "【永】【エントリー】【本領発揮Lv４】：あなたの、メンバーかリタイアに《晶》がいるなら、このキャラを±０/＋２。【自】【エントリー】【本領発揮Lv４】【ターン１】：このキャラがアタックした時、このアタック中、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-079.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-079S": {
    name: "リュウ・メイファン",
    description:
      "【永】【エントリー】【本領発揮Lv４】：あなたの、メンバーかリタイアに《晶》がいるなら、このキャラを±０/＋２。【自】【エントリー】【本領発揮Lv４】【ターン１】：このキャラがアタックした時、このアタック中、このキャラを＋２/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-079s.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-080": {
    name: "火の神 メイファン",
    description:
      "【キャンセル】：Reバース以外の【スパーク】（手札から控え室に置くと、Reバース以外の【スパーク】を１つ止める）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-080.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-080S": {
    name: "火の神 メイファン",
    description:
      "【キャンセル】：Reバース以外の【スパーク】（手札から控え室に置くと、Reバース以外の【スパーク】を１つ止める）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-080s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-081": {
    name: "ベル 栞",
    description:
      "【起】【メンバー】【Reコンボ】《美女と麗しの野獣》【本領発揮Lv４】【ターン１】：［手札から１枚控え室に置く］ あなたの手札が４枚以下なら、あなたは１枚引き、自分のエントリーから〔シークフェルト音楽学院〕を１枚選び、手札に戻す。（コストを払った後に手札を数える）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-081.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-081SP": {
    name: "ベル 栞",
    description:
      "【起】【メンバー】【Reコンボ】《美女と麗しの野獣》【本領発揮Lv４】【ターン１】：［手札から１枚控え室に置く］ あなたの手札が４枚以下なら、あなたは１枚引き、自分のエントリーから〔シークフェルト音楽学院〕を１枚選び、手札に戻す。（コストを払った後に手札を数える）",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-081sp.png",
    atk: 3,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-082": {
    name: "親指姫 栞",
    description:
      "【スパーク】：あなたは味方のメンバーからすべて選び、このターン中、それらは相手から選ばれない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-082.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-082S": {
    name: "親指姫 栞",
    description:
      "【スパーク】：あなたは味方のメンバーからすべて選び、このターン中、それらは相手から選ばれない。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-082s.png",
    atk: 5,
    hp: 6,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-083": {
    name: "夢大路 栞",
    description:
      "【自】【エントリー】：あなたの《文》がメンバーから控え室に置かれた時、あなたはこのキャラをエントリーから空席のメンバーに置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-083.png",
    atk: 5,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-083S": {
    name: "夢大路 栞",
    description:
      "【自】【エントリー】：あなたの《文》がメンバーから控え室に置かれた時、あなたはこのキャラをエントリーから空席のメンバーに置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-083s.png",
    atk: 5,
    hp: 7,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-084": {
    name: "風の神 栞",
    description:
      "【スパーク】【本領発揮Lv３】：あなたは自分の、パートナーかエネルギーから１枚選び、【スタンド】する。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-084.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-084S": {
    name: "風の神 栞",
    description:
      "【スパーク】【本領発揮Lv３】：あなたは自分の、パートナーかエネルギーから１枚選び、【スタンド】する。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-084s.png",
    atk: 3,
    hp: 2,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-085": {
    name: "アルセーヌ・ルパン やちよ",
    description:
      "【スパーク】【本領発揮Lv３】：あなたは自分のメンバーから〔シークフェルト音楽学院〕を１枚選び、控え室に置くことで、相手のメンバーから１枚選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-085.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-085SP": {
    name: "アルセーヌ・ルパン やちよ",
    description:
      "【スパーク】【本領発揮Lv３】：あなたは自分のメンバーから〔シークフェルト音楽学院〕を１枚選び、控え室に置くことで、相手のメンバーから１枚選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-085sp.png",
    atk: 4,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-086": {
    name: "大地の神 やちよ",
    description:
      "【自】【メンバー】：このキャラがサポートした時、あなたはこのキャラをデッキの下に置くことで、１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-086.png",
    atk: 2,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-086S": {
    name: "大地の神 やちよ",
    description:
      "【自】【メンバー】：このキャラがサポートした時、あなたはこのキャラをデッキの下に置くことで、１枚引く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-086s.png",
    atk: 2,
    hp: 5,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-087": {
    name: "鶴姫 やちよ",
    description: "【スパーク】：このターン中、このキャラを±０/＋４。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-087.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-087S": {
    name: "鶴姫 やちよ",
    description: "【スパーク】：このターン中、このキャラを±０/＋４。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-087s.png",
    atk: 2,
    hp: 4,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-088": {
    name: "貂蝉 やちよ",
    description:
      "【自】【メンバー】【本領発揮Lv４】：このキャラがサポートした時、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-088.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-088S": {
    name: "貂蝉 やちよ",
    description:
      "【自】【メンバー】【本領発揮Lv４】：このキャラがサポートした時、このアタック中、サポートされたキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-088s.png",
    atk: 2,
    hp: 3,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-089": {
    name: "大道具室のアーサー王！？",
    description:
      "【スパーク】：あなたは１点回復する。【永】：各ターン１回目のアタック中、あなたのエントリーを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-089.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-089SR＋": {
    name: "大道具室のアーサー王！？",
    description:
      "【スパーク】：あなたは１点回復する。【永】：各ターン１回目のアタック中、あなたのエントリーを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-089sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-090": {
    name: "一人は皆のために",
    description:
      "【スパーク】：あなたは２枚引く。【永】：各ターン１回目のアタック中、あなたのエントリーを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-090.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-090SR＋": {
    name: "一人は皆のために",
    description:
      "【スパーク】：あなたは２枚引く。【永】：各ターン１回目のアタック中、あなたのエントリーを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-090sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-091": {
    name: "友情と悲しみの騎士二人",
    description:
      "【スパーク】：あなたは相手の、エントリーとメンバーから、あなたのリタイアと同じ枚数選び、控え室に置く。（選べる限り選ぶ）【永】：あなたのエントリーを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-091.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-091SR＋": {
    name: "友情と悲しみの騎士二人",
    description:
      "【スパーク】：あなたは相手の、エントリーとメンバーから、あなたのリタイアと同じ枚数選び、控え室に置く。（選べる限り選ぶ）【永】：あなたのエントリーを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-091sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-092": {
    name: "ファントムとクリスティーヌ",
    description:
      "【スパーク】：あなたは自分の控え室からキャラの【スパーク】を１つまで選ぶ。このReバースをセットすることで、このカードの【スパーク】として発動させる。【起】【ターン１】：［エントリーから１枚控え室に置く］ このターン中、次にあなたのエントリーに置かれるキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-092.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-092SR＋": {
    name: "ファントムとクリスティーヌ",
    description:
      "【スパーク】：あなたは自分の控え室からキャラの【スパーク】を１つまで選ぶ。このReバースをセットすることで、このカードの【スパーク】として発動させる。【起】【ターン１】：［エントリーから１枚控え室に置く］ このターン中、次にあなたのエントリーに置かれるキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-092sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-093": {
    name: "月夜のデュエット",
    description:
      "【スパーク】：あなたは味方のメンバーから２枚まで選び、控え室に置く。【自】：このReバースがセットされた時、あなたのリタイアが３枚以上なら、あなたは相手の、エントリーかメンバーから１枚選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-093.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-093SR＋": {
    name: "月夜のデュエット",
    description:
      "【スパーク】：あなたは味方のメンバーから２枚まで選び、控え室に置く。【自】：このReバースがセットされた時、あなたのリタイアが３枚以上なら、あなたは相手の、エントリーかメンバーから１枚選び、控え室に置く。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-093sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-094": {
    name: "トリック・オア・トリート",
    description:
      "【スパーク】：あなたは自分のデッキの上から２枚エネルギーに【レスト】で置く。【永】：各ターン１回目のアタック中、あなたのエントリーを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-094.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-094SR＋": {
    name: "トリック・オア・トリート",
    description:
      "【スパーク】：あなたは自分のデッキの上から２枚エネルギーに【レスト】で置く。【永】：各ターン１回目のアタック中、あなたのエントリーを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-094sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-095": {
    name: "「浦島太郎」公演のお知らせ",
    description: "【永】：あなたのエントリーを＋２/＋３。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-095.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-095SR＋": {
    name: "「浦島太郎」公演のお知らせ",
    description: "【永】：あなたのエントリーを＋２/＋３。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-095sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-096": {
    name: "帝都の平和を守るもの達",
    description:
      "【スパーク】：あなたは自分のデッキの上から２枚エネルギーに【レスト】で置く。【永】：各ターン１回目のアタック中、あなたのエントリーを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-096.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-096SR＋": {
    name: "帝都の平和を守るもの達",
    description:
      "【スパーク】：あなたは自分のデッキの上から２枚エネルギーに【レスト】で置く。【永】：各ターン１回目のアタック中、あなたのエントリーを＋３/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-096sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-097": {
    name: "私色に染まった卵",
    description:
      "【スパーク】：あなたは相手の、エントリーとメンバーから、あなたのリタイアと同じ枚数選び、控え室に置く。（選べる限り選ぶ）【永】：あなたのエントリーを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-097.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-097SR＋": {
    name: "私色に染まった卵",
    description:
      "【スパーク】：あなたは相手の、エントリーとメンバーから、あなたのリタイアと同じ枚数選び、控え室に置く。（選べる限り選ぶ）【永】：あなたのエントリーを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-097sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-098": {
    name: "新シンデレラは正義の味方！",
    description:
      "【スパーク】：あなたは自分の控え室からキャラの【スパーク】を１つまで選ぶ。このReバースをセットすることで、このカードの【スパーク】として発動させる。【起】【ターン１】：［エントリーから１枚控え室に置く］ このターン中、次にあなたのエントリーに置かれるキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-098.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-098SR＋": {
    name: "新シンデレラは正義の味方！",
    description:
      "【スパーク】：あなたは自分の控え室からキャラの【スパーク】を１つまで選ぶ。このReバースをセットすることで、このカードの【スパーク】として発動させる。【起】【ターン１】：［エントリーから１枚控え室に置く］ このターン中、次にあなたのエントリーに置かれるキャラを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-098sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-099": {
    name: "乙女の髪結い",
    description:
      "【キャンセル】：【スパーク】or【キャンセル】（手札から控え室に置くと、【スパーク】か【キャンセル】を１つ止める）【永】：あなたのエントリーを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-099.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-099SR＋": {
    name: "乙女の髪結い",
    description:
      "【キャンセル】：【スパーク】or【キャンセル】（手札から控え室に置くと、【スパーク】か【キャンセル】を１つ止める）【永】：あなたのエントリーを＋１/＋１。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-099sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-100": {
    name: "美女と麗しの野獣",
    description:
      "【スパーク】：あなたは１点回復する。【永】：各ターン１回目のアタック中、あなたのエントリーを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-100.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-100SR＋": {
    name: "美女と麗しの野獣",
    description:
      "【スパーク】：あなたは１点回復する。【永】：各ターン１回目のアタック中、あなたのエントリーを＋１/±０。",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-100sr.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P001": {
    name: "愛城 華恋",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p001.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P001SP": {
    name: "愛城 華恋",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p001sp.png",
    atk: 0,
    hp: 0,
    type: "partner",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P002": {
    name: "神楽 ひかり",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p002.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P002SP": {
    name: "神楽 ひかり",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p002sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P003": {
    name: "天堂 真矢",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p003.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P003SP": {
    name: "天堂 真矢",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p003sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P004": {
    name: "星見 純那",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p004.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P004SP": {
    name: "星見 純那",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p004sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P005": {
    name: "露崎 まひる",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p005.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P005SP": {
    name: "露崎 まひる",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p005sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P006": {
    name: "大場 なな",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p006.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P006SP": {
    name: "大場 なな",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p006sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P007": {
    name: "西條 クロディーヌ",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p007.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P007SP": {
    name: "西條 クロディーヌ",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p007sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P008": {
    name: "石動 双葉",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p008.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P008SP": {
    name: "石動 双葉",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p008sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P009": {
    name: "花柳 香子",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p009.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P009SP": {
    name: "花柳 香子",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p009sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P010": {
    name: "巴 珠緒",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p010.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P010SP": {
    name: "巴 珠緒",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p010sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P011": {
    name: "音無 いちえ",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p011.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P011SP": {
    name: "音無 いちえ",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p011sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P012": {
    name: "夢大路 文",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p012.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P012SP": {
    name: "夢大路 文",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p012sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P013": {
    name: "秋風 塁",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p013.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P013SP": {
    name: "秋風 塁",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p013sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P014": {
    name: "田中 ゆゆ子",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p014.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P014SP": {
    name: "田中 ゆゆ子",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p014sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P015": {
    name: "大月 あるる",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p015.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P015SP": {
    name: "大月 あるる",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p015sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P016": {
    name: "叶 美空",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p016.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P016SP": {
    name: "叶 美空",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p016sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P017": {
    name: "野々宮 ララフィン",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p017.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P017SP": {
    name: "野々宮 ララフィン",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p017sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P018": {
    name: "恵比寿 つかさ",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p018.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P018SP": {
    name: "恵比寿 つかさ",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p018sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P019": {
    name: "胡蝶 静羽",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p019.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P019SP": {
    name: "胡蝶 静羽",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p019sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P020": {
    name: "雪代 晶",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p020.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P020SP": {
    name: "雪代 晶",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p020sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P021": {
    name: "鳳 ミチル",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p021.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P021SP": {
    name: "鳳 ミチル",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p021sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P022": {
    name: "リュウ・メイファン",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p022.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P022SP": {
    name: "リュウ・メイファン",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p022sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P023": {
    name: "夢大路 栞",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p023.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P023SP": {
    name: "夢大路 栞",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p023sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P024": {
    name: "鶴姫 やちよ",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p024.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
  "RS/001B-P024SP": {
    name: "鶴姫 やちよ",
    description: "",
    image_url:
      "https://rebirth-fy.com/wordpress/wp-content/images/cardlist/RSBP/rs001b-p024sp.png",
    atk: 0,
    hp: 0,
    type: "character",
    subtype: "member",
    is_first_entry: false,
  },
};

export function getCardDefinition(
  serialNumber: string
): CardDefinition | undefined {
  return cardDatabase[serialNumber];
}
